{
 "title": "Des_Dashboard",
 "time": { "from": "2022-01-02T00:00:00.000Z", "to": "2023-02-14T21:05:32.900Z" },
 "templating": {
  "list": [
   {
    "name": "SourceSystem",
    "label": "Source System",
    "query": "SELECT DISTINCT jt.source_systems as 'Source System' FROM grafana_data.jira_tickets jt\nWHERE source_systems != ''\nAND source_systems not in ('Advatnage', 'All', 'no', 'other', 'N/A', 'cascadiaequine', 'ElizabethBishop', 'AvantikaKarki', \"MisheScott\", 'AvantikaKarki', 'psivpm', 'ginger')\norder by source_systems"
   },
   {
    "name": "FROM_YEAR",
    "label": "From Year",
    "query": "SELECT DISTINCT YEAR(FROM_UNIXTIME(created)) AS `Year` FROM grafana_data.jira_tickets jt ORDER BY `Year`"
   },
   {
    "name": "FROM_ISO_WEEK",
    "label": "From ISO Week",
    "query": "SELECT DISTINCT WEEK(FROM_UNIXTIME(created)) AS `Week` FROM grafana_data.jira_tickets jt ORDER BY `Week`"
   },
   {
    "name": "TO_YEAR",
    "label": "To Year",
    "query": "SELECT DISTINCT YEAR(FROM_UNIXTIME(created)) AS `Year` FROM grafana_data.jira_tickets jt ORDER BY `Year`"
   },
   {
    "name": "TO_ISO_WEEK",
    "label": "To ISO Week",
    "query": "SELECT DISTINCT WEEK(FROM_UNIXTIME(created)) AS `Week` FROM grafana_data.jira_tickets jt ORDER BY `Week`"
   },
   {
    "name": "Status",
    "label": "Status",
    "query": "SELECT DISTINCT status FROM grafana_data.jira_tickets WHERE `type` IN (\"Pre Conversion Data Fix\", \"Post Conversion Data Fix\");"
   }
  ]
 },
 "panels": [
  {
   "title": "Hours allocated: $SourceSystem, $FROM_YEAR W$FROM_ISO_WEEK - $TO_YEAR W$TO_ISO_WEEK",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "queryMode": "Metrics",
     "rawSql": "SELECT  jt.source_systems, jt.`type`, jt.status, \r\n SUM(IF(jt.resolved > 0, jw.duration/3600 , 0 )) AS 'Trial Ticket Hours spent'\r\nFROM grafana_data.jira_worklogs jw \r\nLEFT JOIN grafana_data.jira_tickets jt ON jw.jiraticketid = jt.id\r\nWHERE jt.ticketnumber LIKE 'CONV-%'\r\nAND jt.`type` LIKE 'Pre Conversion Data Fix%'\r\nAND jt.source_systems IN ($SourceSystem)\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)\r\n",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT  jt.source_systems, jt.`type`, jt.status, \r\n SUM(IF(jt.resolved > 0, jw.duration/3600 , 0 )) AS 'Production Ticket Hours spent'\r\nFROM grafana_data.jira_worklogs jw \r\nLEFT JOIN grafana_data.jira_tickets jt ON jw.jiraticketid = jt.id\r\nWHERE jt.ticketnumber LIKE 'CONV-%'\r\nAND jt.`type` LIKE 'Post Conversion Data Fix%'\r\nAND jt.source_systems IN ($SourceSystem)\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)"
    },
    {}
   ]
  },
  {
   "title": "Trial/Production Tickets Created: $SourceSystem, $FROM_YEAR W$FROM_ISO_WEEK - $TO_YEAR W$TO_ISO_WEEK",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "queryMode": "Metrics",
     "rawSql": "SELECT COUNT(jt.ticketnumber) AS 'Trial Tickets', jt.source_systems, jt.`type` \r\nFROM grafana_data.jira_worklogs jw \r\nLEFT JOIN grafana_data.jira_tickets jt ON jw.jiraticketid = jt.id\r\nWHERE jt.ticketnumber LIKE 'CONV-%'\r\nAND jt.`type` LIKE 'Pre Conversion Data Fix%'\r\nAND jt.source_systems IN ($SourceSystem)\r\nAND jt.status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT COUNT(jt.ticketnumber) AS 'Production Tickets', jt.source_systems, jt.`type` FROM grafana_data.jira_worklogs jw \r\nLEFT JOIN grafana_data.jira_tickets jt ON jw.jiraticketid = jt.id\r\nWHERE jt.ticketnumber LIKE 'CONV-%'\r\nAND jt.`type` LIKE 'Post Conversion Data Fix%'\r\nAND jt.source_systems IN ($SourceSystem)\r\nAND jt.status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)"
    }
   ]
  },
  {
   "title": "Trends Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "grafana_data",
     "queryMode": "Metrics",
     "rawSql": "SELECT\r\n  DATE(FROM_UNIXTIME(jt.created)) AS \"Created Date\", source_systems,\r\n  COUNT(*) AS 'Pre-Conversion'\r\nFROM \r\n  grafana_data.jira_tickets jt\r\nWHERE jt.type = 'Pre Conversion Data Fix'\r\nAND source_systems IN ($SourceSystem )\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)\r\nGROUP BY date(FROM_UNIXTIME(jt.created))\r\n",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT\r\n  DATE(FROM_UNIXTIME(jt.created)) AS \"Created Date\",\r\n  COUNT(*) AS 'Post-Conversion'\r\nFROM \r\n  grafana_data.jira_tickets jt\r\nWHERE jt.type = 'Post Conversion Data Fix'\r\nAND source_systems IN ($SourceSystem )\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)\r\nGROUP BY date(FROM_UNIXTIME(jt.created))"
    }
   ]
  },
  {
   "title": "Trial Tickets per Source System ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "grafana_data",
     "rawSql": "SELECT source_systems, COUNT(ticketnumber) AS 'numberOfTIckets', FROM_UNIXTIME(created), FROM_UNIXTIME(resolved)\r\nFROM grafana_data.jira_tickets \r\nWHERE ticketnumber LIKE 'CONV-%'\r\nAND `type` LIKE 'Pre Conversion Data Fix%'\r\nAND epic IS NOT NULL\r\nAND source_systems <> ''\r\nAND source_systems IN ($SourceSystem)\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)\r\nGROUP BY source_systems "
    }
   ]
  },
  {
   "title": "Production Tickets per Source System",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "queryMode": "Metrics",
     "rawSql": "SELECT source_systems, COUNT(ticketnumber) AS 'numberOfTIckets', FROM_UNIXTIME(created), FROM_UNIXTIME(resolved)\r\nFROM grafana_data.jira_tickets \r\nWHERE ticketnumber LIKE 'CONV-%'\r\nAND `type` LIKE 'Post Conversion Data Fix%'\r\nAND epic IS NOT NULL\r\nAND source_systems <> ''\r\nAND source_systems IN ($SourceSystem)\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)\r\nGROUP BY source_systems ",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Debug panel",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tDISTINCT \r\n\tYEAR(FROM_UNIXTIME(created)) AS `Year`,\r\n\tWEEK(FROM_UNIXTIME(created)) AS `Week`,\r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) AS 'value'\r\nFROM\r\n\tgrafana_data.jira_tickets jt\r\n\tWHERE\r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\n\tAND \r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)"
    }
   ]
  },
  {
   "title": "Average Number of Trial and Production tickets per project",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "queryMode": "Metrics",
     "rawSql": "SELECT\r\n\tROUND(AVG(pre_conv.`Number of Tickets`), 2) AS 'Average Trial Tickets per project',\r\n\tROUND(AVG(post_conv.`Number of Tickets`), 2) AS 'Average Production Tickets per project'\r\nFROM\r\n\t(\r\n\tSELECT\r\n\t\tjt.`epic` AS 'Epic Ticket',\r\n\t\tCOUNT(*) AS 'Number of Tickets'\r\n\tFROM\r\n\t\tgrafana_data.jira_tickets jt\r\n\tWHERE\r\n\t\tjt.ticketnumber LIKE 'CONV-%'\r\n\t\tAND jt.type = 'Pre Conversion Data Fix'\r\n\t\tAND jt.status IN ('Done', 'No Work Required')\r\n\t\tAND jt.`epic` IS NOT NULL\r\n\tGROUP BY\r\n\t\tjt.epic) AS pre_conv\r\n\tLEFT JOIN\r\n\t(\r\n\tSELECT\r\n\t\tjt.`epic` AS 'Epic Ticket',\r\n\t\tCOUNT(*) AS 'Number of Tickets'\r\n\tFROM\r\n\t\tgrafana_data.jira_tickets jt\r\n\tWHERE\r\n\t\tjt.ticketnumber LIKE 'CONV-%'\r\n\t\tAND jt.type = 'Post Conversion Data Fix'\r\n\t\tAND jt.status IN ('Done', 'No Work Required')\r\n\t\t\tAND jt.`epic` IS NOT NULL\r\n\t\tGROUP BY\r\n\t\t\tjt.epic) AS post_conv \r\n\tON pre_conv.`Epic Ticket` = post_conv.`Epic Ticket`;",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Trial Hours spent on $SourceSystem ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana_data",
     "queryMode": "Metrics",
     "rawSql": "SELECT SUM(IF(jt.resolved > 0, jw.duration/3600 , 0 )) AS 'Trial Ticket Hours spent'\r\nFROM grafana_data.jira_worklogs jw \r\nLEFT JOIN grafana_data.jira_tickets jt ON jw.jiraticketid = jt.id\r\nWHERE jt.ticketnumber LIKE 'CONV-%'\r\nAND jt.`type` LIKE 'Pre Conversion Data Fix%'\r\nAND jt.source_systems IN ($SourceSystem)\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)",
     "region": "default",
     "statistic": "Average"
    },
    {
     "rawSql": "SELECT SUM(IF(jt.resolved > 0, jw.duration/3600 , 0 )) AS 'Production Ticket Hours spent'\r\nFROM grafana_data.jira_worklogs jw \r\nLEFT JOIN grafana_data.jira_tickets jt ON jw.jiraticketid = jt.id\r\nWHERE jt.ticketnumber LIKE 'CONV-%'\r\nAND jt.`type` LIKE 'Post Conversion Data Fix%'\r\nAND jt.source_systems IN ($SourceSystem)\r\nAND status IN ($Status)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nAND CAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)"
    }
   ]
  },
  {
   "title": "What do you get when a cow jumps over a barbed wire fence?",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "Select 'Complete and Udder Destruction'"
    }
   ]
  },
  {
   "title": "$SourceSystem Trial/Production Tickets raised from $FROM_YEAR W$FROM_ISO_WEEK to $TO_YEAR W$TO_ISO_WEEK",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryMode": "Metrics",
     "rawSql": "SELECT source_systems, COUNT(ticketnumber) AS 'Trial Tickets Raised', name, assignee, type, FROM_UNIXTIME(jt.created), status, FROM_UNIXTIME(resolved), epic\r\nFROM grafana_data.jira_tickets jt\r\nWHERE ticketnumber LIKE 'CONV-%'\r\nAND `type` LIKE 'Pre Conversion Data Fix%'\r\nAND epic IS NOT NULL\r\nAND source_systems <> ''\r\nAND source_systems IN ('$SourceSystem')\r\nAND\r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\n\tAND \r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(jt.created)), IF(WEEK(FROM_UNIXTIME(jt.created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(jt.created))), WEEK(FROM_UNIXTIME(jt.created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\nGROUP BY source_systems",
     "region": "default",
     "statistic": "Average"
    },
    {
     "rawSql": "SELECT COUNT(ticketnumber) AS 'Production Tickets raised', source_systems, `type` FROM grafana_data.jira_tickets\r\nWHERE ticketnumber LIKE 'CONV-%'\r\nAND `type` LIKE 'Post Conversion Data Fix%'\r\nAND source_systems LIKE '$SourceSystem'\r\nAND\r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) >= CAST(CONCAT('$FROM_YEAR', LPAD('$FROM_ISO_WEEK', 2, '0')) AS SIGNED)\r\n\tAND \r\n\tCAST(CONCAT(YEAR(FROM_UNIXTIME(created)), IF(WEEK(FROM_UNIXTIME(created)) < 10, CONCAT('0', WEEK(FROM_UNIXTIME(created))), WEEK(FROM_UNIXTIME(created)))) AS SIGNED) <= CAST(CONCAT('$TO_YEAR', LPAD('$TO_ISO_WEEK', 2, '0')) AS SIGNED)\r\n"
    }
   ]
  }
 ]
}